name: Test network perf
on:
  workflow_dispatch:
    inputs:
      instanceType:
        description: "The instance type to test"
        required: true

jobs:
  netperf:
    runs-on: ubuntu-20.04
    env:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
      AWS_REGION: ${{ secrets.AWS_REGION }}
      PULUMI_CONFIG_PASSPHRASE: ${{ secrets.PULUMI_CONFIG_PASSPHRASE }}
      INSTANCE_TYPE: ${{ github.event.inputs.instanceType }}
    steps:
      - uses: actions/checkout@v2.3.4
      - name: Install asdf on the Action Runner
        uses: asdf-vm/actions/setup@v1
        with:
          asdf_branch: "v0.8.0"
      - name: Fetch asdf plugins repo
        uses: asdf-vm/actions/plugins-add@v1
      - name: Install just pulumi
        run: |
          asdf install pulumi

      - name: Run test for ${{ github.event.inputs.instanceType }}
        working-directory: operations
        run: |
          npm ci
          pulumi login --cloud-url s3://abatilo/infra/ec2throughput
          pulumi stack init ${INSTANCE_TYPE} || pulumi stack select ${INSTANCE_TYPE}
          pulumi config set aws:region ${AWS_REGION}
          pulumi config set clientInstanceType ${INSTANCE_TYPE}
          pulumi update --yes --skip-preview --suppress-outputs --suppress-permalink

      - name: Waiting for test to execute
        run: |
          sleep 4500

      - name: Destroy stack
        working-directory: operations
        run: |
          pulumi destroy --yes
          pulumi stack rm ${INSTANCE_TYPE} --yes
  redeploy:
    needs:
      - netperf
    runs-on: ubuntu-20.04
    steps:
      # Re-clone so that we deploy the latest version. In case changes were
      # made since the test was started an hour ago
      - uses: actions/checkout@v2.3.4
      - uses: amondnet/vercel-action@v20
        with:
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.ORG_ID}}
          vercel-project-id: ${{ secrets.PROJECT_ID}}
          vercel-args: "--prod"
          github-token: ${{ secrets.GITHUB_TOKEN }}
